### ISSUE TITLE
Crashes during `init run_config` when in a git repo

### ISSUE THREAD

**Issue by raphinesse** [parttimenerd/temci#13]
```
$ temci init run_config
[…]
Set some environment variables? [n] 
Traceback (most recent call last):
  File "BIN/temci", line 11, in <module>
    sys.exit(cli_with_error_catching())
  File "FOO/temci/scripts/cli.py", line 890, in cli_with_error_catching
    cli()
  File "FOO/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "FOO/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "FOO/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "FOO/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "FOO/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "FOO/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "FOO/temci/scripts/cli.py", line 302, in run_config
    prompt_run_config()
  File "FOO/temci/scripts/init.py", line 722, in prompt_run_config
    prompt_config("run config", prompt_run_dict)
  File "FOO/temci/scripts/init.py", line 696, in prompt_config
    blocks.append(prompt_dict_func())
  File "FOO/temci/scripts/init.py", line 459, in prompt_run_dict
    working_dir=working_dir)
  File "FOO/temci/scripts/init.py", line 501, in prompt_exec_driver_dict
    vcs = VCSDriver.get_suited_vcs()
  File "FOO/temci/utils/vcs.py", line 51, in get_suited_vcs
    return avcls[0](dir, branch)
  File "FOO/temci/utils/vcs.py", line 315, in __init__
    super().__init__(dir, branch)
  File "FOO/temci/utils/vcs.py", line 27, in __init__
    self.branch = branch or self.get_branch()  # type: str
  File "FOO/temci/utils/vcs.py", line 335, in get_branch
    if self.branch is not None:
AttributeError: 'GitDriver' object has no attribute 'branch'
```

### System Info
temci 0.7.6 (installled with pip3)
Python 3.5.2
Linux 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64

**Comment by raphinesse** [comment]
I wanted to verify this. But I couldn't install from repo. Using following sequence resulted in [this error](http://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind)

```
git clone https://github.com/parttimenerd/temci
cd temci
pip3 install .
```

Installing with the `--egg` option, like suggested in above link, works. But then I noticed that the entry points were not installed into the pip3 `bin` directory. As there seems to be no git version that exactly matches the one released on pip, maybe there were some changes to have the bins that did not make it into the repo?
