### ISSUE TITLE
Error while installing tecmi with python3.10

### ISSUE THREAD

**Issue by lucic71** [parttimenerd/temci#142]
Hi,

I tried to install temci with the following comand:
```
sudo pip3 install temci
```

But I got the following error:
```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-aap4vfz6/fn_6c9f7e162a0344f4946cc3e8a03336f5/setup.py", line 6, in <module>
          import fn
        File "/tmp/pip-install-aap4vfz6/fn_6c9f7e162a0344f4946cc3e8a03336f5/fn/__init__.py", line 1, in <module>
          from .stream import Stream
        File "/tmp/pip-install-aap4vfz6/fn_6c9f7e162a0344f4946cc3e8a03336f5/fn/stream.py", line 9, in <module>
          from .iters import map, range
        File "/tmp/pip-install-aap4vfz6/fn_6c9f7e162a0344f4946cc3e8a03336f5/fn/iters.py", line 2, in <module>
          from collections import deque, Iterable
      ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
      [end of output]
```

It seems that the Iterable abstract class was removed from collections in Python 3.10, see [this](https://docs.python.org/3/whatsnew/3.10.html#removed).

**Comment by parttimenerd** [comment]
Are you willing to try to fix it with a PR?
