### ISSUE TITLE
temci hates firm

### ISSUE THREAD

**Issue by Kha** [parttimenerd/temci#45]
```
$ temci short exec 'sleep 1'
Benchmark 2 times                 [####################################]  100%          
sleep 1              (    2 single benchmarks)
	 avg_mem_usage      mean =          0.0(0), deviation =   0.0
	 avg_res_set        mean =          0.0(0), deviation =   0.0
	 etime              mean =          1.0(0), deviation = 0.00000%
	 max_res_set        mean =     23(66).(00), deviation = 1.43702%
	 stime              mean =          0.0(0), deviation =   0.0
	 utime              mean =          0.0(0), deviation =   0.0
Traceback (most recent call last):
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/bin/.temci-wrapped", line 11, in <module>
    sys.exit(run())
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/scripts/run.py", line 13, in run
    cli_with_error_catching()
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/scripts/cli.py", line 986, in cli_with_error_catching
    cli_with_verb_arg_handling()
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/scripts/cli.py", line 974, in cli_with_verb_arg_handling
    cli()
  File "/nix/store/5n96lf0l2lcb05aiykq96p78zfxc8kvg-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/5n96lf0l2lcb05aiykq96p78zfxc8kvg-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/5n96lf0l2lcb05aiykq96p78zfxc8kvg-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/5n96lf0l2lcb05aiykq96p78zfxc8kvg-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/5n96lf0l2lcb05aiykq96p78zfxc8kvg-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/5n96lf0l2lcb05aiykq96p78zfxc8kvg-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/scripts/cli.py", line 238, in exec
    temci__short__exec(list(commands), **kwargs)
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/scripts/cli.py", line 264, in temci__short__exec
    benchmark_and_exit(runs)
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/scripts/cli.py", line 193, in benchmark_and_exit
    processor.benchmark()
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/run/run_processor.py", line 199, in benchmark
    self.store_and_teardown()
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/run/run_processor.py", line 267, in store_and_teardown
    self.store()
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/run/run_processor.py", line 298, in store
    chown(f)
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/utils/sudo_utils.py", line 27, in chown
    return chown(path.name)
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/utils/sudo_utils.py", line 29, in chown
    os.chown(path, *get_bench_uid_and_gid())
  File "/nix/store/zx50didvp2m8p7k1dfk7md5h8ikp44ms-temci-local/lib/python3.7/site-packages/temci/utils/sudo_utils.py", line 19, in get_bench_uid_and_gid
    pwnam = getpwnam(get_bench_user())
KeyError: "getpwnam(): name not found: 'firm'"
```

**Comment by Kha** [comment]
Note that there is no reason to call `chown` in the first place here
