### ISSUE TITLE
Stack trace with perf_stat

### ISSUE THREAD

**Issue by qznc** [parttimenerd/temci#6]
```sh
➤ temci short exec -wd "ls" -wd "ls --color" --out out.yaml --runner=perf_stat
[16:42:09] The following plugins are disabled because they need root privileges: nice
[16:42:09] CPUSet functionality is disabled because root privileges are missing.
Benchmark 20 to 100 times         [#######-----------------------------]   21%  0d 00:00:10
Traceback (most recent call last):
  File "/usr/local/bin/temci", line 9, in <module>
    load_entry_point('temci==0.7.1', 'console_scripts', 'temci')()
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/scripts/cli.py", line 882, in cli_with_error_catching
    cli()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/scripts/cli.py", line 205, in exec
    temci__short__exec(**kwargs)
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/scripts/cli.py", line 234, in temci__short__exec
    RunProcessor(runs).benchmark()
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/run/run_processor.py", line 184, in benchmark
    self.store_and_teardown()
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/run/run_processor.py", line 240, in store_and_teardown
    report = ReporterRegistry.get_for_name("console", self.stats_helper)\
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/utils/registry.py", line 45, in get_for_name
    return cls.registry[name](misc_settings, *args, **kwargs)
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/report/report.py", line 79, in __init__
    self.stats = TestedPairsAndSingles(self.stats_helper.valid_runs())  # type: TestedPairsAndSingles
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/report/stats.py", line 1003, in __init__
    for prop in self.properties():
TypeError: 'NoneType' object is not iterable
```

It fails deterministically at 21%.

**Comment by parttimenerd** [comment]
Does this happen withe the `time` runner too?

**Comment by qznc** [comment]
No stack trace with `time`. Well, `perf stat` on the command line works.

**Comment by parttimenerd** [comment]
I can't reproduce your bug. Does the new commit help?

**Comment by qznc** [comment]
Seems to work now. No idea why that commit fixed it...
