### ISSUE TITLE
Stack trace with report

### ISSUE THREAD

**Issue by qznc** [parttimenerd/temci#8]
```sh
➤ temci report out.yaml
Traceback (most recent call last):
  File "/usr/local/bin/temci", line 9, in <module>
    load_entry_point('temci==0.7.1', 'console_scripts', 'temci')()
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/scripts/cli.py", line 882, in cli_with_error_catching
    cli()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/scripts/cli.py", line 244, in report
    temci__report(*args, **kwargs)
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/scripts/cli.py", line 250, in temci__report
    ReportProcessor().report()
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/report/report_processor.py", line 21, in report
    self.reporter.report()
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/report/report.py", line 695, in report
    inner_html += self._full_single_property_comp_table().html()
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/report/report.py", line 778, in _full_single_property_comp_table
    table = _Table(self, header_cells, header_cells, _Cell(self, "vs."))
  File "/afs/info.uni-karlsruhe.de/user/zwinkau/dev/temci/temci/report/report.py", line 1826, in __init__
    assert len(header_row) > 0
AssertionError
```
The input is [out.yaml](https://github.com/parttimenerd/temci/files/248662/out.yaml.txt).

This issue is a followup of #6, it now breaks at report generation.

The assert was added with 5d51df7e.

**Comment by parttimenerd** [comment]
As the out.yaml file doesn't contain any valid properties (besides the implementation specific `__ov-time` temci tells you that something is wrong with you data.

**Comment by parttimenerd** [comment]
temci now fails with a (readable) error message to prevent any confusion.
