### ISSUE TITLE
temci exec crashes on block error

### ISSUE THREAD

**Issue by Kha** [parttimenerd/temci#81]
```
$ temci exec
[21:09:36] Forced teardown of RunProcessor
Traceback (most recent call last):
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/pdb.py", line 1701, in main
    pdb._runscript(mainpyfile)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/pdb.py", line 1570, in _runscript
    self.run(statement)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/nix/store/58il93dbz7na12djnwz3fmwyb6gvn5ak-temci-local/bin/.temci-wrapped", line 11, in <module>
    sys.exit(run())
  File "/nix/store/58il93dbz7na12djnwz3fmwyb6gvn5ak-temci-local/lib/python3.7/site-packages/temci/scripts/run.py", line 13, in run
    cli_with_error_catching()
  File "/nix/store/58il93dbz7na12djnwz3fmwyb6gvn5ak-temci-local/lib/python3.7/site-packages/temci/scripts/cli.py", line 999, in cli_with_error_catching
    cli_with_verb_arg_handling()
  File "/nix/store/58il93dbz7na12djnwz3fmwyb6gvn5ak-temci-local/lib/python3.7/site-packages/temci/scripts/cli.py", line 987, in cli_with_verb_arg_handling
    cli()
  File "/nix/store/b0sg528h0v1ajgxc0xawc8hrmhxqbzz1-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 823, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/b0sg528h0v1ajgxc0xawc8hrmhxqbzz1-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 776, in main
    rv = self.invoke(ctx)
  File "/nix/store/b0sg528h0v1ajgxc0xawc8hrmhxqbzz1-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1201, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/b0sg528h0v1ajgxc0xawc8hrmhxqbzz1-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1020, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/b0sg528h0v1ajgxc0xawc8hrmhxqbzz1-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 585, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/58il93dbz7na12djnwz3fmwyb6gvn5ak-temci-local/lib/python3.7/site-packages/temci/scripts/cli.py", line 214, in _func
    globals()["temci__" + driver](*args, **kwargs)
  File "/nix/store/58il93dbz7na12djnwz3fmwyb6gvn5ak-temci-local/lib/python3.7/site-packages/temci/scripts/cli.py", line 220, in _func2
    benchmark_and_exit()
  File "/nix/store/58il93dbz7na12djnwz3fmwyb6gvn5ak-temci-local/lib/python3.7/site-packages/temci/scripts/cli.py", line 201, in benchmark_and_exit
    processor.benchmark()
  File "/nix/store/58il93dbz7na12djnwz3fmwyb6gvn5ak-temci-local/lib/python3.7/site-packages/temci/run/run_processor.py", line 205, in benchmark
    self._benchmarking_block_run(run=run_count)
  File "/nix/store/58il93dbz7na12djnwz3fmwyb6gvn5ak-temci-local/lib/python3.7/site-packages/temci/run/run_processor.py", line 256, in _benchmarking_block_run
    self.stats_helper.add_data_block(id, result.data)
  File "/nix/store/58il93dbz7na12djnwz3fmwyb6gvn5ak-temci-local/lib/python3.7/site-packages/temci/report/rundata.py", line 594, in add_data_block
    self.runs[program_id].add_data_block(data_block)
AttributeError: 'NoneType' object has no attribute 'add_data_block'
```

**Comment by Kha** [comment]
Why? Because the third line here tries to access a run the first line has just set to `None`:
https://github.com/parttimenerd/temci/blob/master/temci/run/run_processor.py#L254-L256
